// Mint a non-expiring Facebook Page access token for the social post publisher.
//
//   node scripts/facebook-token.mjs            # write into .env.local
//   node scripts/facebook-token.mjs --print    # print only, touch nothing
//
// The App Secret and the short-lived user token are read from hidden prompts.
// Neither is written to disk, echoed, or kept after the exchange — only the
// resulting Page token is persisted. FB_APP_ID, FB_APP_SECRET, FB_USER_TOKEN
// and FB_PAGE_ID answer the corresponding prompt when set, for a run with no
// terminal; prefix such a command with a space to keep it out of shell history.
//
// Chain: short-lived user token --(exchange)--> long-lived user token
//        --(/<user id>/accounts)--> Page token, which does not expire.
//
// The Explorer hands out USER tokens; the Page token is derived here, not
// copied from the Explorer.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline";

const GRAPH = "https://graph.facebook.com/v21.0";
const ENV_PATH = resolve(process.cwd(), ".env.local");
const PRINT_ONLY = process.argv.includes("--print");

function die(message) {
  console.error(`\n✖ ${message}`);
  process.exit(1);
}

function readEnv() {
  if (!existsSync(ENV_PATH)) return {};
  return Object.fromEntries(
    readFileSync(ENV_PATH, "utf8")
      .split("\n")
      .filter((l) => !l.trimStart().startsWith("#") && l.includes("="))
      .map((l) => {
        const i = l.indexOf("=");
        return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
      }),
  );
}

// One readline for the whole run, with an explicit line queue. A fresh
// interface per question swallows input already buffered behind the current
// line, and question() is one-shot: when stdin is a pipe every line arrives in
// one chunk, so later lines are emitted and dropped before the next question
// registers.
const isTty = Boolean(process.stdin.isTTY);
const rl = createInterface({ input: process.stdin, output: process.stdout, terminal: isTty });

const pending = [];
const waiting = [];
rl.on("line", (line) => {
  const next = waiting.shift();
  if (next) next(line);
  else pending.push(line);
});

// stdin can end before a prompt is answered — notably under a harness that
// gives no interactive terminal. Surface that instead of hanging on an
// unsettled await.
let closed = false;
rl.on("close", () => {
  closed = true;
  while (waiting.length) waiting.shift()(null);
});

let masked = false;

// In terminal mode readline echoes each keystroke through _writeToOutput.
// While a secret is being read, swallow that echo entirely — the question
// itself is written directly to stdout below.
rl._writeToOutput = (chunk) => {
  if (!masked) rl.output.write(chunk);
};

function prompt(question, { secret = false, fallback = "" } = {}) {
  masked = secret && isTty;
  process.stdout.write(question);

  return new Promise((res) => {
    const done = (line) => {
      if (masked) process.stdout.write("\n");
      masked = false;
      if (line === null) {
        die(
          "No input available — this script needs an interactive terminal.\n" +
            "  Run it in your own shell, not through an agent/CI harness. To run it\n" +
            "  non-interactively instead, supply the answers as environment variables:\n\n" +
            "    FB_APP_ID=... FB_APP_SECRET=... FB_USER_TOKEN=... pnpm fb:token\n",
        );
      }
      res(line.trim() || fallback);
    };
    const buffered = pending.shift();
    if (buffered !== undefined) done(buffered);
    else if (closed) done(null);
    else waiting.push(done);
  });
}

async function graph(path, params) {
  const url = `${GRAPH}${path}?${new URLSearchParams(params)}`;
  let body;
  try {
    body = await (await fetch(url)).json();
  } catch (error) {
    die(`Could not reach the Graph API: ${error.message}`);
  }
  if (body.error) die(`Facebook rejected the call: ${body.error.message}`);
  return body;
}

function upsertEnv(values) {
  const original = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, "utf8") : "";
  const keys = Object.keys(values);

  const kept = original
    .split("\n")
    .filter((line) => !keys.some((k) => line.startsWith(`${k}=`)))
    .join("\n")
    .replace(/\n*# Facebook Page posting[^\n]*\n*/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd();

  const block = ["", "# Facebook Page posting — generated by scripts/facebook-token.mjs"]
    .concat(keys.map((k) => `${k}=${values[k]}`))
    .join("\n");

  writeFileSync(ENV_PATH, `${kept}\n${block}\n`, { mode: 0o600 });
}

const env = readEnv();

const appId =
  process.env.FB_APP_ID ||
  (await prompt(`App ID${env.FACEBOOK_APP_ID ? ` [${env.FACEBOOK_APP_ID}]` : ""}: `, {
    fallback: env.FACEBOOK_APP_ID,
  }));
if (!appId) die("App ID is required.");

const appSecret =
  process.env.FB_APP_SECRET || (await prompt("App Secret (hidden): ", { secret: true }));
if (!appSecret) die("App Secret is required. Find it under App settings → Basic → Show.");

const shortToken =
  process.env.FB_USER_TOKEN ||
  (await prompt("Short-lived user token from the Graph API Explorer (hidden): ", {
    secret: true,
  }));
if (!shortToken) die("User token is required.");

console.log("\n→ Exchanging for a long-lived user token…");
const { access_token: longToken } = await graph("/oauth/access_token", {
  grant_type: "fb_exchange_token",
  client_id: appId,
  client_secret: appSecret,
  fb_exchange_token: shortToken,
});
if (!longToken) die("The exchange returned no access_token.");

// Identify the exchanged token before using it. /me is ambiguous — for an app
// token it resolves to the Application node, and asking that for `accounts`
// fails with a misleading "nonexisting field" error. Resolving the user id up
// front turns that into a precise diagnosis.
const { data: exchanged } = await graph("/debug_token", {
  input_token: longToken,
  access_token: longToken,
});

if (exchanged.type !== "USER") {
  die(
    `The exchange returned a ${exchanged.type} token, not a USER token.\n` +
      "  This happens when the value given as the user token was not a user token —\n" +
      "  most often the App Secret pasted into the wrong prompt, or a Page/App token\n" +
      "  copied from the Explorer's token dropdown.\n\n" +
      "  In the Graph API Explorer set 'User or Page' to 'User Token', click\n" +
      "  'Generate Access Token', and use the value from the Access Token field.",
  );
}

if (!exchanged.user_id) die("Facebook returned a USER token with no user_id.");

console.log(`→ Listing Pages for user ${exchanged.user_id}…`);
const { data: pages = [] } = await graph(`/${exchanged.user_id}/accounts`, {
  fields: "name,id,access_token,tasks",
  access_token: longToken,
});

const publishable = pages.filter((p) => (p.tasks ?? []).includes("CREATE_CONTENT"));
if (publishable.length === 0) {
  die(
    "No Page grants CREATE_CONTENT. Re-run the Explorer step and tick the target Page in the\n" +
      "  consent dialog, with the pages_manage_posts scope selected.",
  );
}

console.log("");
publishable.forEach((p, i) => console.log(`  ${i + 1}. ${p.name}  (${p.id})`));

const choice =
  publishable.length === 1
    ? "1"
    : process.env.FB_PAGE_ID
      ? String(publishable.findIndex((p) => p.id === process.env.FB_PAGE_ID) + 1)
      : await prompt(`\nWhich Page? [1-${publishable.length}]: `, { fallback: "1" });

const page = publishable[Number(choice) - 1];
if (!page) die(`No Page at index ${choice}.`);

console.log(`\n→ Verifying the Page token for ${page.name}…`);
const { data: info } = await graph("/debug_token", {
  input_token: page.access_token,
  access_token: page.access_token,
});

if (info.type !== "PAGE") die(`Expected a PAGE token, got ${info.type}.`);
if (!info.is_valid) die("Facebook reports the derived Page token is not valid.");
if (!(info.scopes ?? []).includes("pages_manage_posts")) {
  die("The Page token lacks pages_manage_posts — publishing would fail.");
}
if (info.expires_at !== 0) {
  console.warn(
    `\n⚠ This token expires ${new Date(info.expires_at * 1000).toISOString()} rather than never.\n` +
      "  That means the user token was still short-lived — the exchange did not take effect.",
  );
}

console.log(`
  Page:    ${page.name}
  ID:      ${page.id}
  Type:    ${info.type}
  Expires: ${info.expires_at === 0 ? "never" : new Date(info.expires_at * 1000).toISOString()}
  Scopes:  ${(info.scopes ?? []).join(", ")}
`);

if (PRINT_ONLY) {
  console.log(`FACEBOOK_PAGE_ID=${page.id}`);
  console.log(`FACEBOOK_PAGE_ACCESS_TOKEN=${page.access_token}`);
} else {
  upsertEnv({ FACEBOOK_PAGE_ID: page.id, FACEBOOK_PAGE_ACCESS_TOKEN: page.access_token });
  console.log(`✓ Wrote FACEBOOK_PAGE_ID and FACEBOOK_PAGE_ACCESS_TOKEN to ${ENV_PATH}`);
}

rl.close();
